config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  constraints :subdomain => "cp" do
    scope :module => "cp", :as => "cp" do
      resources :brands
      resources :categories
      resources :products
      resources :subcategories
      resources :subsubcategories
      resources :users do
        member do
          put 'change_admin_status'
          get 'change_admin_status'
        end
      end
      root "products#index"
    end
  end

  scope :module => "fe", :as => "fe" do
    resources :comments
    root "static_pages#main"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :users
  belongs_to :products
end

app/controllers/fe/comments_controller.rb
class Fe::CommentsController < ApplicationController
  before_action :set_fe_comment, only: [:show, :edit, :update, :destroy]

  # GET /fe/comments
  # GET /fe/comments.json
  def index
    @fe_comments = Comment.all
  end

  # GET /fe/comments/1
  # GET /fe/comments/1.json
  def show
  end

  # GET /fe/comments/new
  def new
    @fe_comment = Comment.new
  end

  # GET /fe/comments/1/edit
  def edit
  end

  # POST /fe/comments
  # POST /fe/comments.json
  def create
    @fe_comment = Comment.new(fe_comment_params)

    respond_to do |format|
      if @fe_comment.save
        format.html { redirect_to @fe_comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @fe_comment }
      else
        format.html { render :new }
        format.json { render json: @fe_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fe/comments/1
  # PATCH/PUT /fe/comments/1.json
  def update
    respond_to do |format|
      if @fe_comment.update(fe_comment_params)
        format.html { redirect_to @fe_comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @fe_comment }
      else
        format.html { render :edit }
        format.json { render json: @fe_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fe/comments/1
  # DELETE /fe/comments/1.json
  def destroy
    @fe_comment.destroy
    respond_to do |format|
      format.html { redirect_to fe_comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fe_comment
      @fe_comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fe_comment_params
      params.require(:comment).permit(:users_id, :title, :description)
    end
end

app/controllers/fe/products_controller.rb
class Fe::ProductsController < ApplicationController



  def show
    @product = Product.find(params[:id])


  end

end

app/controllers/fe/static_pages_controller.rb
class Fe::StaticPagesController < ApplicationController
  def main
  end
end

app/helpers/fe/comments_helper.rb
module Fe::CommentsHelper
end

app/helpers/fe/products_helper.rb
module Fe::ProductsHelper
end

app/helpers/fe/static_pages_helper.rb
module Fe::StaticPagesHelper
end

app/views/fe/comments/_form.html.slim
= simple_form_for(@fe_comment) do |f|
  = f.error_notification

  .form-inputs
    = f.association :users
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/fe/comments/edit.html.slim
h1 Editing fe_comment

== render 'form'

= link_to 'Show', @fe_comment
'|
= link_to 'Back', fe_comments_path

app/views/fe/comments/index.html.slim
h1 Listing fe_comments

table
  thead
    tr
      th Users
      th Title
      th Description
      th
      th
      th

  tbody
    - @fe_comments.each do |fe_comment|
      tr
        td = fe_comment.users
        td = fe_comment.title
        td = fe_comment.description
        td = link_to 'Show', fe_comment
        td = link_to 'Edit', edit_fe_comment_path(fe_comment)
        td = link_to 'Destroy', fe_comment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Comment', new_fe_comment_path

app/views/fe/comments/new.html.slim
h1 New fe_comment

== render 'form'

= link_to 'Back', fe_comments_path

app/views/fe/comments/show.html.slim
p#notice = notice

p
  strong Users:
  = @fe_comment.users
p
  strong Title:
  = @fe_comment.title
p
  strong Description:
  = @fe_comment.description

= link_to 'Edit', edit_fe_comment_path(@fe_comment)
'|
= link_to 'Back', fe_comments_path