config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  constraints :subdomain => "cp" do
    scope :module => "cp", :as => "cp" do
      resources :brands
      resources :categories
      resources :products
      resources :subcategories
      resources :subsubcategories
      resources :users do
        member do
          put 'change_admin_status'
          get 'change_admin_status'
        end
      end
      root "products#index"
    end
  end

  scope :module => "fe", :as => "fe" do
    resources :comments
    root "static_pages#main"
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_many :subcategories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :users
  belongs_to :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brands
  belongs_to :categories
  has_many :comments
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :categories
  has_many :subsubcategories
end

app/models/subsubcategory.rb
class Subsubcategory < ActiveRecord::Base
  belongs_to :subcategories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include LocalSubdomain
  protect_from_forgery with: :exception

end

app/controllers/cp/admins_controller.rb
class Cp::AdminsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  layout "cp"

  def check_if_admin
    if user_signed_in? && current_user.isAdmin == true
      cp_root_path
    else
      new_user_session_path
    end
  end
end

app/controllers/cp/brands_controller.rb
class Cp::BrandsController < Cp::AdminsController
  before_action :set_cp_brand, only: [:show, :edit, :update, :destroy]

  # GET /cp/brands
  # GET /cp/brands.json
  def index
    @cp_brands = Brand.all
    @title = "Brands"
  end

  # GET /cp/brands/1
  # GET /cp/brands/1.json
  def show
  end

  # GET /cp/brands/new
  def new
    @cp_brand = Brand.new
  end

  # GET /cp/brands/1/edit
  def edit
  end

  # POST /cp/brands
  # POST /cp/brands.json
  def create
    @cp_brand = Brand.new(cp_brand_params)

    respond_to do |format|
      if @cp_brand.save
        format.html { redirect_to @cp_brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @cp_brand }
      else
        format.html { render :new }
        format.json { render json: @cp_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cp/brands/1
  # PATCH/PUT /cp/brands/1.json
  def update
    respond_to do |format|
      if @cp_brand.update(cp_brand_params)
        format.html { redirect_to @cp_brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @cp_brand }
      else
        format.html { render :edit }
        format.json { render json: @cp_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cp/brands/1
  # DELETE /cp/brands/1.json
  def destroy
    @cp_brand.destroy
    respond_to do |format|
      format.html { redirect_to cp_brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cp_brand
      @cp_brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cp_brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/controllers/cp/users_controller.rb
class Cp::UsersController < Cp::AdminsController
  def index
    @users = User.order(:isAdmin)
    @title = "Users"
  end

  def change_admin_status
    @user = User.find(params[:id])
    if @user.isAdmin == true
      @user.isAdmin = false
    else
      @user.isAdmin = true
    end
    respond_to do |format|
      if @user.save!
        format.html { redirect_to cp_users_url }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cp/brands_helper.rb
module Cp::BrandsHelper
end

app/helpers/cp/categories_helper.rb
module Cp::CategoriesHelper
end

app/helpers/cp/products_helper.rb
module Cp::ProductsHelper
end

app/helpers/cp/subcategories_helper.rb
module Cp::SubcategoriesHelper
end

app/helpers/cp/users_helper.rb
module Cp::UsersHelper
end

app/helpers/fe/comments_helper.rb
module Fe::CommentsHelper
end

app/helpers/fe/products_helper.rb
module Fe::ProductsHelper
end

app/helpers/fe/static_pages_helper.rb
module Fe::StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
<!--header-->
<div class="header" id="header">
<div class="container">
    <div class="head">
      <div class="logo">
        <a href=<%= "#{fe_root_path}" %>><%= image_tag "logo.png", class: "sticking-logo" %></a>
      </div>
    </div>
  </div>
  <div class="header-top">
    <div class="container">
    <div class="col-sm-5 col-md-offset-2  header-login">
          <ul >
            <%- unless user_signed_in? %>
            <li><%= link_to('Login', new_user_session_path)  %> </li>
            <li><%= link_to('Register', new_user_registration_path)  %></li>
            <%- else %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <li><a href="checkout.html">Checkout</a></li>
            <% end %>
          </ul>
        </div>

      <div class="col-sm-5 header-social">
          <ul >
            <li><a href="#"><i></i></a></li>
            <li><a href="#"><i class="ic1"></i></a></li>
            <li><a href="#"><i class="ic2"></i></a></li>
            <li><a href="#"><i class="ic3"></i></a></li>
            <li><a href="#"><i class="ic4"></i></a></li>
          </ul>

      </div>
        <div class="clearfix"> </div>
    </div>
    </div>

    <div class="container">

      <div class="head-top">

     <div class="col-sm-8 col-md-offset-2 h_menu4">
        <nav class="navbar nav_bottom" role="navigation">

 <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header nav_2">
      <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

   </div>
   <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
        <ul class="nav navbar-nav nav_1">
            <li><a class="color" href="index.html">Home</a></li>

        <li class="dropdown mega-dropdown active">
          <a class="color1" href="#" class="dropdown-toggle" data-toggle="dropdown">Women<span class="caret"></span></a>
        <div class="dropdown-menu ">
                    <div class="menu-top">
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu1</h4>
                  <ul>
                    <li><a href="product.html">Accessories</a></li>
                    <li><a href="product.html">Bags</a></li>
                    <li><a href="product.html">Caps & Hats</a></li>
                    <li><a href="product.html">Hoodies & Sweatshirts</a></li>

                  </ul>
              </div>
            </div>
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu2</h4>
                <ul>
                    <li><a href="product.html">Jackets & Coats</a></li>
                    <li><a href="product.html">Jeans</a></li>
                    <li><a href="product.html">Jewellery</a></li>
                    <li><a href="product.html">Jumpers & Cardigans</a></li>
                    <li><a href="product.html">Leather Jackets</a></li>
                    <li><a href="product.html">Long Sleeve T-Shirts</a></li>
                  </ul>
              </div>
            </div>
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu3</h4>
                  <ul>
                    <li><a href="product.html">Shirts</a></li>
                    <li><a href="product.html">Shoes, Boots & Trainers</a></li>
                    <li><a href="product.html">Sunglasses</a></li>
                    <li><a href="product.html">Sweatpants</a></li>
                    <li><a href="product.html">Swimwear</a></li>
                    <li><a href="product.html">Trousers & Chinos</a></li>

                  </ul>

              </div>
            </div>
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu4</h4>
                <ul>
                  <li><a href="product.html">T-Shirts</a></li>
                  <li><a href="product.html">Underwear & Socks</a></li>
                  <li><a href="product.html">Vests</a></li>
                  <li><a href="product.html">Jackets & Coats</a></li>
                  <li><a href="product.html">Jeans</a></li>
                  <li><a href="product.html">Jewellery</a></li>
                </ul>
              </div>
            </div>
            <div class="col1 col5">
            <%= image_tag "me.png", class: "img-responsive" %>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </li>
      <li class="dropdown mega-dropdown active">
          <a class="color2" href="#" class="dropdown-toggle" data-toggle="dropdown">Men<span class="caret"></span></a>
        <div class="dropdown-menu mega-dropdown-menu">
                    <div class="menu-top">
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu1</h4>
                  <ul>
                    <li><a href="product.html">Accessories</a></li>
                    <li><a href="product.html">Bags</a></li>
                    <li><a href="product.html">Caps & Hats</a></li>
                    <li><a href="product.html">Hoodies & Sweatshirts</a></li>

                  </ul>
              </div>
            </div>
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu2</h4>
                <ul>
                    <li><a href="product.html">Jackets & Coats</a></li>
                    <li><a href="product.html">Jeans</a></li>
                    <li><a href="product.html">Jewellery</a></li>
                    <li><a href="product.html">Jumpers & Cardigans</a></li>
                    <li><a href="product.html">Leather Jackets</a></li>
                    <li><a href="product.html">Long Sleeve T-Shirts</a></li>
                  </ul>
              </div>
            </div>
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu3</h4>

<ul>
                    <li><a href="product.html">Shirts</a></li>
                    <li><a href="product.html">Shoes, Boots & Trainers</a></li>
                    <li><a href="product.html">Sunglasses</a></li>
                    <li><a href="product.html">Sweatpants</a></li>
                    <li><a href="product.html">Swimwear</a></li>
                    <li><a href="product.html">Trousers & Chinos</a></li>

                  </ul>

              </div>
            </div>
            <div class="col1">
              <div class="h_nav">
                <h4>Submenu4</h4>
                <ul>
                  <li><a href="product.html">T-Shirts</a></li>
                  <li><a href="product.html">Underwear & Socks</a></li>
                  <li><a href="product.html">Vests</a></li>
                  <li><a href="product.html">Jackets & Coats</a></li>
                  <li><a href="product.html">Jeans</a></li>
                  <li><a href="product.html">Jewellery</a></li>
                </ul>
              </div>
            </div>
            <div class="col1 col5">
            <%= image_tag "me1.png", class: "img-responsive" %>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </li>
      <li><a class="color3" href="product.html">Sale</a></li>
      <li><a class="color4" href="404.html">About</a></li>
            <li><a class="color5" href="typo.html">Short Codes</a></li>
            <li ><a class="color6" href="contact.html">Contact</a></li>
        </ul>
     </div><!-- /.navbar-collapse -->

</nav>
      </div>
      <div class="col-sm-2 search-right">
        <ul class="heart">
        <li>
        <a href="wishlist.html" >
        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        </a></li>
        <li><a class="play-icon popup-with-zoom-anim" href="#small-dialog"><i class="glyphicon glyphicon-search"> </i></a></li>
          </ul>
          <div class="cart box_1">
            <a href="checkout.html">
            <h3> <div class="total">
              <span class="simpleCart_total"></span></div>
              <%= image_tag "cart.png" %></h3>
            </a>
            <p><a href="javascript:;" class="simpleCart_empty">Empty Cart</a></p>

          </div>
          <div class="clearfix"> </div>

            <!----->

            <!---pop-up-box---->

      <!---//pop-up-box---->
      <div id="small-dialog" class="mfp-hide">
        <div class="search-top">
          <div class="login-search">
            <input type="submit" value="">
            <input type="text" value="Search.." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search..';}">
          </div>
          <p>Shopin</p>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

<%= yield %>
<!--//footer-->
<div class="footer">
<div class="footer-middle">
    <div class="container">
      <div class="col-md-3 footer-middle-in">
        <a href="index.html"><%= image_tag "log.png" %></a>
        <p>Suspendisse sed accumsan risus. Curabitur rhoncus, elit vel tincidunt elementum, nunc urna tristique nisi, in interdum libero magna tristique ante. adipiscing varius. Vestibulum dolor lorem.</p>
      </div>

      <div class="col-md-3 footer-middle-in">
        <h6>Information</h6>
        <ul class=" in">
          <li><a href="404.html">About</a></li>
          <li><a href="contact.html">Contact Us</a></li>
          <li><a href="#">Returns</a></li>
          <li><a href="contact.html">Site Map</a></li>
        </ul>
        <ul class="in in1">
          <li><a href="#">Order History</a></li>
          <li><a href="wishlist.html">Wish List</a></li>
          <li><a href="login.html">Login</a></li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="col-md-3 footer-middle-in">
        <h6>Tags</h6>
        <ul class="tag-in">
          <li><a href="#">Lorem</a></li>
          <li><a href="#">Sed</a></li>
          <li><a href="#">Ipsum</a></li>
          <li><a href="#">Contrary</a></li>
          <li><a href="#">Chunk</a></li>
          <li><a href="#">Amet</a></li>
          <li><a href="#">Omnis</a></li>
        </ul>
      </div>
      <div class="col-md-3 footer-middle-in">
        <h6>Newsletter</h6>
        <span>Sign up for News Letter</span>
          <form>
            <input type="text" value="Enter your E-mail" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='Enter your E-mail';}">
            <input type="submit" value="Subscribe">
          </form>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <ul class="footer-bottom-top">
        <li><a href="#"><%= image_tag "f1.png", class: "img-responsive" %></a></li>
        <li><a href="#"><%= image_tag "f2.png", class: "img-responsive" %></a></li>
        <li><a href="#"><%= image_tag "f3.png", class: "img-responsive" %></a></li>
      </ul>
      <p class="footer-class">&copy; <%= Time.now.year %> OnShop.by All Rights Reserved | Design by  <a href="https://vk.com/fucking_shitass" target="_blank">Simonenkov</a> </p>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<!--//footer-->
</body>
</html>

app/views/layouts/cp.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <style>
  body {
    margin-top: 100px;
    background-color: #222;
}

@media(min-width:768px) {
    body {
        margin-top: 50px;
    }
}

#wrapper {
    padding-left: 0;
}

#page-wrapper {
    width: 100%;
    padding: 0;
    background-color: #fff;
}

.huge {
    font-size: 50px;
    line-height: normal;
}

@media(min-width:768px) {
    #wrapper {
        padding-left: 225px;
    }

    #page-wrapper {
        padding: 10px;
    }
}

/* Top Navigation */

.top-nav {
    padding: 0 15px;
}

.top-nav>li {
    display: inline-block;
    float: left;
}

.top-nav>li>a {
    padding-top: 15px;
    padding-bottom: 15px;
    line-height: 20px;
    color: #999;
}

.top-nav>li>a:hover,
.top-nav>li>a:focus,
.top-nav>.open>a,
.top-nav>.open>a:hover,
.top-nav>.open>a:focus {
    color: #fff;
    background-color: #000;
}

.top-nav>.open>.dropdown-menu {
    float: left;
    position: absolute;
    margin-top: 0;
    border: 1px solid rgba(0,0,0,.15);
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    background-color: #fff;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}

.top-nav>.open>.dropdown-menu>li>a {
    white-space: normal;
}

ul.message-dropdown {
    padding: 0;
    max-height: 250px;
    overflow-x: hidden;
    overflow-y: auto;
}

li.message-preview {
    width: 275px;
    border-bottom: 1px solid rgba(0,0,0,.15);
}

li.message-preview>a {
    padding-top: 15px;
    padding-bottom: 15px;
}

li.message-footer {
    margin: 5px 0;
}

ul.alert-dropdown {
    width: 200px;
}

/* Side Navigation */

@media(min-width:768px) {
    .side-nav {
        position: fixed;
        top: 51px;
        left: 225px;
        width: 225px;
        margin-left: -225px;
        border: none;
        border-radius: 0;
        overflow-y: auto;
        background-color: #222;
        bottom: 0;
        overflow-x: hidden;
        padding-bottom: 40px;
    }

    .side-nav>li>a {
        width: 225px;
    }

    .side-nav li a:hover,
    .side-nav li a:focus {
        outline: none;
        background-color: #000 !important;
    }
}

.side-nav>li>ul {
    padding: 0;
}

.side-nav>li>ul>li>a {
    display: block;
    padding: 10px 15px 10px 38px;
    text-decoration: none;
    color: #999;
}

.side-nav>li>ul>li>a:hover {
    color: #fff;
}

/* Flot Chart Containers */

.flot-chart {
    display: block;
    height: 400px;
}

.flot-chart-content {
    width: 100%;
    height: 100%;
}

/* Custom Colored Panels */

.huge {
    font-size: 40px;
}

.panel-green {
    border-color: #5cb85c;
}

.panel-green > .panel-heading {
    border-color: #5cb85c;
    color: #fff;
    background-color: #5cb85c;
}

.panel-green > a {
    color: #5cb85c;
}

.panel-green > a:hover {
    color: #3d8b3d;
}

.panel-red {
    border-color: #d9534f;
}

.panel-red > .panel-heading {
    border-color: #d9534f;
    color: #fff;
    background-color: #d9534f;
}

.panel-red > a {
    color: #d9534f;
}

.panel-red > a:hover {
    color: #b52b27;
}

.panel-yellow {
    border-color: #f0ad4e;
}

.panel-yellow > .panel-heading {
    border-color: #f0ad4e;
    color: #fff;
    background-color: #f0ad4e;
}

.panel-yellow > a {
    color: #f0ad4e;
}

.panel-yellow > a:hover {
    color: #df8a13;
}
  </style>
</head>
<body>



    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= cp_root_url %>">OnShop.by Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.email %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>

                            <%= link_to destroy_user_session_path, :method => :delete do %>
                            <i class="fa fa-fw fa-power-off"></i> Logout
                            <% end %>


                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li <%- if @title == "Products"%>class="active" <% end %>>
                        <%= link_to cp_products_url do %>
                          <i class="fa fa-fw fa-dashboard"></i> Products
                        <% end %>

                    </li>
                    <li <%- if @title == "Categories"%>class="active" <% end %>>
                        <%= link_to cp_categories_url do %>
                          <i class="fa fa-fw fa-bar-chart-o"></i> Categories
                        <% end %>

                    </li >
                    <li <%- if @title == "Users"%>class="active" <% end %>>
                        <%= link_to cp_users_url do %>
                            <i class="fa fa-fw fa-table"></i> Users
                        <% end %>

                    </li>
                    <li>
                        <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Forms</a>
                    </li>
                    <li>
                        <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
                    </li>
                    <li>
                        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
                    </li>
                    <li>
                        <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">


                <!-- /.row -->
  <%= yield %>



</body>
</html>